### PR TITLE
Wordpress-Mariadb example for ansible-container.

### PR DESCRIPTION
**Pull request by procrypt**
# \- Feature Pull Request  
- It is a simple Wordpress-Mariadb example based on Centos 7 for ansible-container.
- It creates wordpress database with wordpress user on  database container and connects it to wordpress container.
- Works fine on Kubernetes and OpenShift.

main.yml

```
-  hosts: db
   vars:
     - wp_mysql_db: wordpress
     - wp_mysql_user: wordpress
     - wp_mysql_password: password
```

```
-  hosts: wordpress
   vars:
     - wp_mysql_db: wordpress
     - wp_mysql_user: wordpress
     - wp_mysql_password: password

```

We can change the user and database by editing the main.yml file.

main.yml

```
-  hosts: db
   vars:
     - wp_mysql_db: < database name >
     - wp_mysql_user: < user name >
     - wp_mysql_password: < password >
```

```
-  hosts: wordpress
   vars:
     - wp_mysql_db: < database name >
     - wp_mysql_user: < user name >
     - wp_mysql_password: < password >
```
## Build Images.

```
$ cd example/wordpress-example
$ ansible-container build
```
## Run the Container.

```
$ ansible-container run

```
## Push the images to cloud.

```
$ docker login
$ ansible-container push

```
## Deploy to OpenShift.

```
$ ansible-container shipit openshift --save-config

Images will be pulled from procrypto
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Role wordpress created.

```

It will create the OpenShift artifacts to deploy it on OpenShift.
## Run the OpenShift Artifacts.

```
$ oc create -f wordpress/ansible/shipit_config/openshift/

route "db-3306" created
deploymentconfig "db" created
service "db" created
route "wordpress-80" created
deploymentconfig "wordpress" created
service "wordpress" created

```
## View the Services and Deployments on OpenShift.

```
$ oc get service
NAME        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
db          172.30.32.159   <none>        3306/TCP   3h
wordpress   172.30.47.102   <none>        80/TCP     3h

```
## Next, take a look at the pods created by the deployments.

```
$ oc get pods
NAME                READY     STATUS    RESTARTS   AGE
db-1-0xob4          1/1       Running   0          3h
wordpress-1-9wp23   1/1       Running   0          3h

```
## Details of one of the pods.

```
$ oc describe pod wordpress-1-9wp23 
Name:       wordpress-1-9wp23
Namespace:  sample-project
Node:       adb.vm/192.168.121.210
Start Time: Thu, 25 Aug 2016 01:58:28 -0400
Labels:     app=wordpress,deployment=wordpress-1,deploymentconfig=wordpress,service=wordpress
Status:     Running
IP:     172.17.0.6
Controllers:    ReplicationController/wordpress-1
Containers:
  wordpress:
    Container ID:   docker://49192ac035b01e56632a2090ee05695ffba54dc93ddfd45312486c4568775d56
    Image:      procrypto/wordpress-wordpress:20160822144236
    Image ID:       docker://8012c285060d102987cfbcc4b6a6220bc1037ab4d5b74b0de1568f43d6495f32
    Port:       80/TCP
    Args:
      bash
      -c
      bash /tmp/a.sh ; usr/sbin/apachectl -D FOREGROUND
    QoS Tier:
      memory:       BestEffort
      cpu:      BestEffort
    State:      Running
      Started:      Thu, 25 Aug 2016 02:01:57 -0400
    Ready:      True
    Restart Count:  0
    Environment Variables:
Conditions:
  Type      Status
  Ready     True 
Volumes:
  default-token-4s5b8:
    Type:   Secret (a volume populated by a Secret)
    SecretName: default-token-4s5b8
```
## Deploy to Kubernetes.

```
$ ansible-container shipit kube --save-config

Images will be pulled from procrypto
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Role wordpress created.

```

It will create the Kubernetes artifacts to deploy it on Kubernetes.
## Run the Kubernetes Artifacts.

```
$ kubectl create -f wordpress/ansible/shipit_config/kubernetes/

deployment "db" created
service "db" created
deployment "wordpress" created
service "wordpress" created

```
## View the Services on Kubernetes.

```
$ kubectl get service

NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
db           10.254.176.204   <none>        3306/TCP   1m
kubernetes   10.254.0.1       <none>        443/TCP    2d
wordpress    10.254.177.169   <none>        80/TCP     1m

```
## View the Deployments.

```
$ kubectl get deployment 
NAME        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
db          1         1         1            1           4m
wordpress   1         1         1            1           4m
```
## Next, take a look at the pods created by the deployments.

```
$ kubectl get pods
NAME                         READY     STATUS    RESTARTS   AGE
db-1420940741-bluto          1/1       Running   0          1m
wordpress-1256450439-vqksz   1/1       Running   0          1m

```
## Details of one of the pods.

```
$ kubectl describe pod wordpress-1256450439-vqksz 
Name:       wordpress-1256450439-vqksz
Namespace:  default
Node:       127.0.0.1/127.0.0.1
Start Time: Thu, 25 Aug 2016 05:58:12 -0400
Labels:     app=wordpress,pod-template-hash=1256450439,service=wordpress
Status:     Running
IP:     172.17.0.3
Controllers:    ReplicaSet/wordpress-1256450439
Containers:
  wordpress:
    Container ID:   docker://03136dc3b4aa204bc8f0e3c1811ed061ccb7b7f9bb8d3a6e1d7cd12c40f14767
    Image:      procrypto/wordpress-wordpress:20160822144236
    Image ID:       docker://8012c285060d102987cfbcc4b6a6220bc1037ab4d5b74b0de1568f43d6495f32
    Port:       80/TCP
    Args:
      bash
      -c
      bash /tmp/a.sh ; usr/sbin/apachectl -D FOREGROUND
    QoS Tier:
      cpu:      BestEffort
      memory:       BestEffort
    State:      Running
      Started:      Thu, 25 Aug 2016 05:58:19 -0400
    Ready:      True
    Restart Count:  0
    Environment Variables:
Conditions:
  Type      Status
  Ready     True 
Volumes:
  default-token-61sic:
    Type:   Secret (a volume populated by a Secret)
    SecretName: default-token-61sic
```

### CODE REVIEW

**Comment by dustymabe** [comment]
Hey @procrypt - I was able to get this example running on my local setup. I do have some comments but want to wait until I've had time to fully try out alternatives before I make the comments. I hope to have those to you by tomorrow.

**Comment by procrypt** [comment]
@dustymabe Thanks for the review :)

**Comment by chouseknecht** [comment]
I don't mean to be difficult, but similar comment as before. How is this better than using stock Docker Hub or OpenShift images? In other words, why build a MySql image from scratch when one already exists?

**Comment by chouseknecht** [comment]
Missing a README file.

**Comment by dustymabe** [comment]
hey @chouseknecht, I think it is useful just to show people how to use ansible-container. They see wordpress. They know wordpress. Here's how you do it with ansible-container. Same for the db. In this case I wouldn't mind if we pulled a stock image from somewhere, but having it be a complete example doesn't bother me either.

I know we want more complicated examples to show people what all can be done, but I think having simple ones is actually more useful for people getting started. The django example in the main ansible-container repo was complex and a bit confusing to me.

**Comment by dustymabe** [comment]
@procrypt I'll get you the rest of those comments later today

**Comment by procrypt** [comment]
@dustymabe I'll wait for your comments.

**Comment by chouseknecht** [comment]
First, let me say to @procrypt, thank you for working on this and taking the time to submit it. Please don't get discouraged. What you have submitted shows that you understand the concepts. You obviously know Ansible and Ansible Container, and you've also demonstrated knowledge of Kubernetes. It's smart, and it's technically sound. I'm not in anyway being critical of the work you're doing. My concern is more about user perceptions.

We can use this submission, but I want to simplify it and put the emphasis in the right spot. Bare with me while I explain what I'm thinking...

We keep getting the "playbooks are hard and too complicated" comment, right? I heard that uttered just this morning in our Dev Tools meeting. (It puts me in a bad mood every time too.) So I don't want people to look at this example and think that stock images cannot be used with Ansible Container or that we somehow think/want every image to be built via playbook.

Take a look at the [Docker Compose Wordpress example](https://docs.docker.com/compose/wordpress/). It's a single Docker Compose file consisting of 25 lines. Pretty simple, right? 

What's being proposed here is at first glance not so simple. Again, not a criticism of the work product. Step back and look at it from the point of view of a developer that does not know Ansible and has never used Ansible Container. That person will surely ask, "Where's the value in doing it the Ansible Container way?"

The value proposition I see for this example is to make the simple Wordpress example deployable to OpenShift and Kubernetes. Let's put a laser focus on the deployment. That's something you cannot do with the 25 line docker-compose file.

My suggestion is to use stock images and remove everything possible from the playbook. And I don't know what's possible with Wordpress. I know there is a stock MySql image that works on OpenShift, so use that. Do the simplest thing possible to get a working Wordpress image. Emphasis on simple. If the Wordpress image requires a playbook, that's cool, but explain why in the README (we still need that, btw). Help the user see why we're employing a playbook. Show the value. 

Then get to the money shot - deploy it to OpenShift. Then do the "Look, Mom, No changes!" and deploy it to Kubernetes. And for the deployment, just focus on showing `ansible-container shipit..` and what that produces. Don't bother showing the playbook run, pods, containers. Meh. We want people's attention on `shipit` - that's the thing Docker cannot do. It's simple. It's one line.

Let me know, if you have questions or you think I'm completely nuts. I might be. 

--Chris

**Comment by dustymabe** [comment]
> First, let me say to @procrypt, thank you for working on this and taking the time to submit it. Please don't get discouraged. What you have submitted shows that you understand the concepts. You obviously know Ansible and Ansible Container, and you've also demonstrated knowledge of Kubernetes. It's smart, and it's technically sound. I'm not in anyway being critical of the work you're doing. My concern is more about user perceptions.

Absolutely, nice work @procrypt!

> We can use this submission, but I want to simplify it and put the emphasis in the right spot. Bare with me while I explain what I'm thinking...
> 
> We keep getting the "playbooks are hard and too complicated" comment, right? I heard that uttered just this morning in our Dev Tools meeting. (It puts me in a bad mood every time too.) So I don't want people to look at this example and think that stock images cannot be used with Ansible Container or that we somehow think/want every image to be built via playbook.
> 
> Take a look at the Docker Compose Wordpress example. It's a single Docker Compose file consisting of 25 lines. Pretty simple, right?

right, but I don't know if this is a fair comparison. On the one hand you have the 25 line docker compose file, on the other you have the container.yml (15 lines), and main.yml, where main.yml defines how to build wordpress and mariadb. If we were to compare the docker compose file plus the Dockerfiles that were used to build the "ready made" containers then it starts to be a little more of a fair comparison.

> What's being proposed here is at first glance not so simple. Again, not a criticism of the work product. Step back and look at it from the point of view of a developer that does not know Ansible and has never used Ansible Container. That person will surely ask, "Where's the value in doing it the Ansible Container way?"

and that is something we have to address. If there is no value for the user then they will never choose to do it this way. 

> The value proposition I see for this example is to make the simple Wordpress example deployable to OpenShift and Kubernetes. Let's put a laser focus on the deployment. That's something you cannot do with the 25 line docker-compose file.

So you are saying most of the value is in the "deploy to openshift" part and not the "I can build a container image with an ansible playbook" part? 

> My suggestion is to use stock images and remove everything possible from the playbook. And I don't know what's possible with Wordpress. I know there is a stock MySql image that works on OpenShift, so use that. Do the simplest thing possible to get a working Wordpress image. Emphasis on simple. If the Wordpress image requires a playbook, that's cool, but explain why in the README (we still need that, btw). Help the user see why we're employing a playbook. Show the value.

we can absolutely use the stock image for mariadb. I guess the sentiment was that we wanted to do everything with ansible playbooks because that is the differentiator of the tool we are using. we could even use the stock image for wordpress, but I almost feel like we start to miss the point a little? why would you use this tool if you didn't want to leverage ansible in some way? simply for the deploy to openshift part? 

> Then get to the money shot - deploy it to OpenShift. Then do the "Look, Mom, No changes!" and deploy it to Kubernetes. And for the deployment, just focus on showing ansible-container shipit.. and what that produces. Don't bother showing the playbook run, pods, containers. Meh. We want people's attention on shipit - that's the thing Docker cannot do. It's simple. It's one line.
> 
> Let me know, if you have questions or you think I'm completely nuts. I might be.

you're nuts, but so are we :)

**Comment by chouseknecht** [comment]
> and that is something we have to address. If there is no value for the user then they will never choose to do it this way. 

Yes. We agree that we must address this.

> So you are saying most of the value is in the "deploy to openshift" part and not the "I can build a container image with an ansible playbook" part? 

Just in this case, for this example. To me, when I see this example, I immediately think of the Docker Compose Wordpress example. It's in my head, because when we first started playing with a way to `ship` things to Kubernetes, it was our starting point due to it's basic simplicity. It was easy, ergo shipping it should be easy. I'm biased, but other people know the Docker examples too and will also make the comparison.

> we can absolutely use the stock image for mariadb. I guess the sentiment was that we wanted to do everything with ansible playbooks because that is the differentiator of the tool we are using. 

It's a differentiator, yes. But we can't be the "hammer that's always looking for a nail." Sometimes a playbook makes all the sense in the world. Sometimes it does not. We're running Docker Compose under the hood. We know that because we've all lived in the code. A new user has no idea that basic compose still works, and that it's completely cool to just use a stock image for a service. Sometimes users need permission to do the obvious. 

> we could even use the stock image for wordpress, but I almost feel like we start to miss the point a little? why would you use this tool if you didn't want to leverage ansible in some way? simply for the deploy to openshift part?

I think it's perfectly OK to sometimes, when it makes sense, use Ansible Container just for the`shipit` command. It offers a way to translate compose to Kubernetes/OpenShift and figures out the deployment for me. Seemingly there is value in that. 

There is also value in using a playbook in place of a Dockerfile. But, if I can avoid a Dockerfile and just use a stock image I will. So the point is... let's not write playbooks for the sake of writing playbooks, because all that does is teach people how to write playbooks.

I'm all for demonstrating playbooks where it makes sense. When this original submission came up, I suggested adding additional components to it where it might makes sense to employ a playbook.

For example... If I were a Wordpress developer building templates or writing PHP pluggins, what would I need? I likely would not want the stock Wordpress image. And, I would probably need the containers to behave differently in DEV vs. PROD. In DEV I might want a Gulp process running to compile Javascript/CSS/etc. No idea if something similar would be needed for PHP. But there's probably an ideal DEV environment for PHP. You get my point. That's a way to demonstrate the value and Ansible Container, and that's the type of thing I would love to see.

**Comment by procrypt** [comment]
> First, let me say to @procrypt, thank you for working on this and taking the time to submit it.

Thank You @chouseknecht and @dustymabe for reviewing it and yes working on this example was a good learning experience for me.

> We keep getting the "playbooks are hard and too complicated" comment, right? I heard that uttered just this morning in our Dev Tools meeting. (It puts me in a bad mood every time too.) So I don't want people to look at this example and think that stock images cannot be used with Ansible Container or that we somehow think/want every image to be built via playbook.
> 
> What's being proposed here is at first glance not so simple. Again, not a criticism of the work product. Step back and look at it from the point of view of a developer that does not know Ansible and has never used Ansible Container. That person will surely ask, "Where's the value in doing it the Ansible Container way?"

I agree that the playbook looks very complicated in this example, and we can definitely use the stock images to reduce the complexity of the playbook, but the whole idea was to get a good understanding of how the modules and playbook works in ansible-container.

>  My suggestion is to use stock images and remove everything possible from the playbook. And I don't know what's possible with Wordpress. I know there is a stock MySql image that works on OpenShift, so use that. Do the simplest thing possible to get a working Wordpress image. Emphasis on simple. If the Wordpress image requires a playbook, that's cool, but explain why in the README.

I will try to make this example as simple as possible.

> Then get to the money shot - deploy it to OpenShift. Then do the "Look, Mom, No changes!" and deploy it to Kubernetes. And for the deployment, just focus on showing ansible-container shipit.. and what that produces. Don't bother showing the playbook run, pods, containers. Meh. We want people's attention on shipit - that's the thing Docker cannot do. It's simple. It's one line.
> 
> Let me know, if you have questions or you think I'm completely nuts. I might be.

What ever you said completely make sense, glad my work is appreciated :)

**Pull request merged**
